### ISSUE TITLE
Run DIRAC integration tests in CI

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS#106]
Now that the tests are self contained for GitHub actions it should be simple to add to the GitLab CI pipeline.

I'm happy to implement it but thought I should ask first.

Any thoughts?

**Comment by chaen** [comment]
DIRAC or DIRACOS in the title ? 
We still have the deployment problem with github actions no ?

**Comment by chrisburr** [comment]
DIRAC i.e. further test in Git**Lab** CI that the DIRACOS tarball will work as expected by running the DIRAC integration tests.

>  We still have the deployment problem with github actions no ?

I don't understand?

**Comment by chaen** [comment]
Okay so yes, I am up for it, I wanted to do it too :-)

The second part was in case you wanted to run the DIRACOS build in github actions instead of gitlab-ci

**Comment by chrisburr** [comment]
> The second part was in case you wanted to run the DIRACOS build in github actions instead of gitlab-ci

I've thought about it but the real issue is that I'm not sure there is enough CPU power available...

It might stop being a problem when moving to Python 3 and adding ARM/POWER support but that's a totally separate pile of issues.
