### ISSUE TITLE
Singularity isn't self contained

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS#117]
Currently singularity tries to find it's starter binary in `/usr/libexec/singularity/bin/starter` instead of getting it from DIRACOS. It's found here:

https://github.com/sylabs/singularity/blob/d18eaec3d7d0f0c071f77ffede382474812e66fd/internal/pkg/util/starter/starter.go#L118

**Comment by petricm** [comment]
So what happens if you try to run singularity on a machines that does not have singularity natively?

**Comment by chrisburr** [comment]
It crashes saying `/usr/libexec/singularity/bin/starter` can't be found.
