### ISSUE TITLE
DIRACOS Rucio client libs compatibility - Question

### ISSUE THREAD

**Issue by martynia** [DIRACGrid/DIRACOS#154]
Hi all,
Are Rucio Python libs compatible with a current version of DIRACOS ? I remember @chrisburr mentioned  this issue during our BiLD meeting, not sure what DIRACOS version he meant.

**Comment by petricm** [comment]
If it is pure python I don't know what would the issue, as far as I see the rucio stuff is on pypi

**Comment by chrisburr** [comment]
It should be easy to add to both version of DIRACOS. As I guess you're only interested in DIRACOS 1 for now:

* For development: Run `pip install rucio-clients` after sourcing the `bashrc`
* To make a VO specific extension with Rucio added: https://diracos.readthedocs.io/80_extendingDIRACOS.html
* To add to vanilla DIRACOS: Make a PR to edit [`config/requirements.txt`](https://github.com/DIRACGrid/DIRACOS/blob/master/config/requirements.txt)

**Comment by petricm** [comment]
`rucio-clients` is part of DIRAC os v1r17 onwards
