### ISSUE TITLE
missing libboost_python* in diracOS for CentOS7

### ISSUE THREAD

**Issue by zhangxiaomei** [DIRACGrid/DIRACOS#155]
We are running jobs in CentOS7. When the job tried to send back data, the job got error about lack of  libboost_python-mt.so.1.53.0: 
```
"Can't load GFAL2_SRM2Storage in /scratch/plt00/DIRAC/Resources/Storage
Traceback (most recent call last):
  File "/scratch/plt00/DIRAC/Core/Utilities/ObjectLoader.py", line 94, in __recurseImport
    impModule = imp.load_module(modName[0], *impData)
  File "/scratch/plt00/DIRAC/Resources/Storage/GFAL2_SRM2Storage.py", line 15, in <module>
    import gfal2  # pylint: disable=import-error
ImportError: libboost_python-mt.so.1.53.0: cannot open shared object file: No such file or directory
Failed to load storage object: Failed to import library ( 1001 : Can't load GFAL2_SRM2Storage in /scratch/plt00/DIRAC/Resources/Storage) "
```
The diracos package (we used diracos-v1r3, but even higher version has the same problems for these libraries)  only include libs which belongs to the SL6 system:
../diracos/usr/lib64/libboost_python-mt.so
../diracos/usr/lib64/libboost_python-mt.so.5
../diracos/usr/lib64/libboost_python.so
../diracos/usr/lib64/libboost_python.so.5

Is it possible to add these centos7 libraries to diracos?

**Comment by chaen** [comment]
Hi,

Can you please indicate steps to reproduce the problem ?

Also, please provide us with the output of the following commands:

* `env`
* `which gfal-ls`
* `ldd $DIRACOS/usr/lib64/python2.7/site-packages/gfal2.so`

**Comment by zhangxiaomei** [comment]
Hi, 
I did the check again this week in the jobs and found that the installation made by pilots are not using diracos yet. The pilots are still using dirac-install without "--dirac-os". The external libraries under Linux_x86_64_glibc-2.17 are not so complete and new as diracos. That is the reason which caused the problems of missing .so.  Sorry about misunderstanding on this issue.
