### ISSUE TITLE
"voms-proxy" executables' related links missing

### ISSUE THREAD

**Issue by JacekHoleczek** [DIRACGrid/DIRACOS#166]
On a CentOS 7 / x86_64 machine, I tried the latest dirac_ui version "v7r1p29", which includes "diracos-v1r17".
I noticed that some "voms-proxy" executables' related links are missing, so one needs to:

```bash
cd ./diracos/usr/bin
ln voms-proxy-destroy2 voms-proxy-destroy
ln voms-proxy-info2 voms-proxy-info
ln voms-proxy-init2 voms-proxy-init
# rm voms-proxy-list # a symbolic link to nonexistent "voms-proxy-init"
# ln voms-proxy-init voms-proxy-list
cd -
```

Could you, please, fix it in the "diracos" distribution.

**Comment by fstagni** [comment]
I think we can close this issue with a "won't do for this version".
