### ISSUE TITLE
Add authlib, pyjwt, dominate

### ISSUE THREAD

**Issue by TaykYoku** [DIRACGrid/DIRACOS#178]
It would be good to add the following packages to pass the [#5149](https://github.com/DIRACGrid/DIRAC/pull/5149) tests:
- authlib <= 0.15.3
- pyjwt <= 1.7.1
- dominate

**Comment by petricm** [comment]
I have a bit of problem understanding `authlib>=1.0.0` as the current release is v0.15.3 and on authlib it's written
> We will drop Python 2 support when Authlib 1.0 is released

**Comment by chrisburr** [comment]
There is an alpha release of authlib 1 on PyPI but the setuptools metadata states it's only for Python 3.6+.

Do the new token developments need to support Python 2?

**Comment by fstagni** [comment]
We might as well say that it's only python3, anyway we already can use python3 clients and python3 server is not far away. In this case we don't need DIRACOS support, only DIRACOS2. 
- How far is authlib 1.0?
- What has been installed on oauthcertif machine?

**Comment by TaykYoku** [comment]
Sorry for the delay, I checked on a test installation, we can safely use
```
authlib .__ version__
'0.15.3'
```

**Comment by TaykYoku** [comment]
> We might as well say that it's only python3, anyway we already can use python3 clients and python3 server is not far away. In this case we don't need DIRACOS support, only DIRACOS2.
> 
> * How far is authlib 1.0?
0.15.3 is enough for now
> * What has been installed on oauthcertif machine?
python 2, so the remark is correct, need to use version 0.15.3 now

**Comment by chaen** [comment]
I also would advocate to make it python3 only

**Comment by TaykYoku** [comment]
I have updated the package versions to support py2 and py3

**Comment by chrisburr** [comment]
> How far is authlib 1.0?

Minus 2 months (March). DIRAC will definitely not be ready fast enough so we might as well use 1.0.0a0 and avoid accidentally using deprecated interfaces.

**Comment by chaen** [comment]
(hopping they respect the deadline a bit more than DIRAC :-D )

**Comment by TaykYoku** [comment]
I think [if we agree to stop py2 support](https://github.com/DIRACGrid/DIRAC/pull/5149#discussion_r646719376), we can upgrade authlib and pyjwt packages to the latest versions

**Comment by fstagni** [comment]
> I think [if we agree to stop py2 support](https://github.com/DIRACGrid/DIRAC/pull/5149#discussion_r646719376), we can upgrade authlib and pyjwt packages to the latest versions

In DIRACOS2 only, as DIRACOS will stay for py2 installations.

**Comment by chrisburr** [comment]
> In DIRACOS2 only, as DIRACOS will stay for py2 installations.

There is no need for the packages to be installed in DIRACOS at all

**Comment by TaykYoku** [comment]
So IIUC we can close issue
