### ISSUE TITLE
Specify number of jobs to build

### ISSUE THREAD

**Issue by petricm** [DIRACGrid/DIRACOS#22]
Mock can be instructed to use N cores to build with
```
config_opts['macros']['%_smp_mflags'] = "-j4"
```
it might be worth mentioning this or even better to add the option
```
dos-build-all-rpms -j4 /tmp/DIRACOS/config/diracos.json
```

**Comment by chaen** [comment]
In https://github.com/DIRACGrid/DIRACOS/pull/25
