### ISSUE TITLE
Add release script

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRACOS#30]
@petricm @andresailer 
not urgent at all, but could you help me setup the release script and templates as you did for your DIRAC extension and the DIRAC repo ? 
Thanks !

**Comment by andresailer** [comment]
For the template one just needs to copy this file
https://github.com/DIRACGrid/DIRAC/blob/integration/.github/PULL_REQUEST_TEMPLATE
and modify it
For the release notes script I would add an option to the script in Dirac/docs, that allows one to target other repositories.

GetReleaseNotes --repo DIRACOS ...

**Comment by andresailer** [comment]
I will make sure things are working when no subsystem is specified.

**Comment by chaen** [comment]
Thanks !!

**Comment by chaen** [comment]
in #33
