### ISSUE TITLE
Shrink size of DIRACOS

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRACOS#39]
I already tried various compression level, but we are at the maximum for that. 
By default, we also get ride of all the docs and debug info in the cfg
```
      "excludePatterns": [
         ".*-doc-.*",
         ".*-debuginfo-.*"
      ],
```

So we will have to trim things down one way or another.
I do not want any dirty hack in any case.

**Comment by fstagni** [comment]
Are we still in the ballpark of 300MB after compression and docs removal?

What are the biggest contributors to the space consumption?

**Comment by chaen** [comment]
384M yes. 
python eats up the most space (303M). numpy & matplotlib help a lot for that...

**Comment by chaen** [comment]
Now, If I look at a production server, we are not so much bellow

```
[dirac@lbvobox109 dirac]$ du -sh /opt/dirac/pro/Linux_x86_64_glibc-2.12/
914M    /opt/dirac/pro/Linux_x86_64_glibc-2.12/
```

**Comment by chaen** [comment]
Down to ~256M. More improvement can be done (only a couple of MB) by removing devel packages, but we need the mysql-devel package. So needs a little bit more dev

**Comment by fstagni** [comment]
This, won't happen here.
