### ISSUE TITLE
Can we retire glite and lcg libraries

### ISSUE THREAD

**Issue by chaen** [DIRACGrid/DIRACOS#66]
In v7r0, there is only gfal2 and the new fts3 rest interface, so maybe we can remove those. To be tested

**Comment by fstagni** [comment]
*maybe*.
But, I am afraid that glite is still necessary for CREAM CEs.

**Comment by chaen** [comment]
Is this dependency visible in the code ? How can we check ?

**Comment by atsareg** [comment]
We use glite-ce-job-submit command line tool to submit pilots to CREAM CEs which makes me suspect that this is glite libraries dependent

**Comment by chaen** [comment]
Convincing argument :-) Closing it for now then, thanks !
