### ISSUE TITLE
Upgrade XRootD to  4.10 rc1

### ISSUE THREAD

**Issue by andresailer** [DIRACGrid/DIRACOS#74]
As mentioned in #73 
There is a pre-release ready which fixes the bug: https://github.com/xrootd/xrootd/issues/977#issuecomment-491885262

**Comment by chaen** [comment]
yep, jut did https://github.com/DIRACGrid/DIRACOS/tree/xrootd-4.10-rc1 
I'll try to test that

**Comment by chaen** [comment]
Forgot to say that I tested it, and it solves the issues we were having with xroot. I'll wait for a proper release

**Comment by chaen** [comment]
in https://github.com/DIRACGrid/DIRACOS/pull/98
