### ISSUE TITLE
Can not submit ARC job

### ISSUE THREAD

**Issue by VladimirRomanovsky** [DIRACGrid/DIRACOS#77]
Trying to submit job we have in result

VERBOSE: Running command: arcsub -d DEBUG -c hepgrid5.ph.liv.ac.uk job2.xrsl
VERBOSE: System configuration file (/etc/arc/client.conf or /usr/etc/arc/client.conf) does not exist.
INFO: Cannot copy example configuration (/usr/share/arc/examples/client.conf), it is not a regular file
INFO: No configuration file could be loaded.
INFO: Using proxy file: /home/dirac/testARC/x509up_u15872
INFO: Using CA certificate directory: /etc/grid-security/certificates
DEBUG: Certificate format is PEM
DEBUG: Trying to check X509 cert with check_cert_type
DEBUG: Module Manager Init
ERROR: Invalid JobDescription:
&(executable="test.sh")
(inputFiles=(test.sh "test.sh"))
(stdout="test.out")
(stderr="test.err")
(outputFiles=("test.out" "") ("test.err" ""))

No job description parsers available

It seems ARC does not use plugins despite they are formally "installed".

At lxplus we have during job submission

....
DEBUG: Module Manager Init
DEBUG: Loaded /usr/lib64/arc/libaccJobDescriptionParser.so
DEBUG: Loaded JobDescriptionParserPlugin ARCJSDLParser
DEBUG: Loaded JobDescriptionParserPlugin JDLParser
DEBUG: Loaded JobDescriptionParserPlugin XRSLParser
VERBOSE: String successfully parsed as nordugrid:xrsl.
....

It seems ARC looks for plugins at /usr/lib64/arc only by default.

Resume:
**ARC should be configured somehow**.

**Comment by petricm** [comment]
Can you provide a bit more information. Are you trying to run on CC7 or SLC6? And please attach the whole log output from -ddd.

**Comment by andresailer** [comment]
@VladimirRomanovsky do you have ARC_PLUGIN_PATH in the bashrc?

**Comment by VladimirRomanovsky** [comment]
Hi,

The behavior is the same for slc6 and cents 7. Arc submit command does not
has -did option ;)
You can find logs at ~roma/public/forthright

Thanks,
Vladimir

**Comment by VladimirRomanovsky** [comment]
Obviously not. It should be part of installation of diracos I suppose.
At least I do not configure nothing at lxplus and usual Dirac vobox.

Thanks,
Vladimir

**Comment by chaen** [comment]
Can you try with this envrionment variable ? If it works, we will add it to the bashrc
