### ISSUE TITLE
MySQL 8.0 support

### ISSUE THREAD

**Issue by antolu** [DIRACGrid/DIRACOS#78]
Installation using fullInstall in [DIRAC/tests/Jenkins/dirac_ci.sh](https://github.com/DIRACGrid/DIRAC/blob/integration/tests/Jenkins/dirac_ci.sh) fails when the script wants to create a new DB in MySQL. It seems like MySQL 8 changes default authentication plugin from `mysql_native_password` to `caching_sha2_password`, as mentioned [here](https://stackoverflow.com/questions/49963383/authentication-plugin-caching-sha2-password).
Install log is here: [log.txt](https://github.com/DIRACGrid/DIRAC/files/3300247/log.txt).

The following environment variables were used:
```
DEBUG=True
DIRAC_RELEASE=v6r22-pre3
DB_USER=Dirac
DB_PASSWORD=Dirac
DB_ROOTUSER=admin
DB_ROOTPWD=password
DB_HOST=172.18.0.4
DB_PORT=3306
DIRACOSVER=v1r1

NoSQLDB_HOST=172.18.0.5
NoSQLDB_PORT=9200

repository=DIRACGrid
branch=rel-v6r22
DIRACBRANCH=rel-v6r22
```
as well as having MySQL 8.0 and ElasticSearch 6.6.0 in separate Docker containers. The server was also installed in a Docker container. The admin user in docker was created using

```
CREATE USER 'admin'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
quit
```

Solutions to this include:
1. Upgrading MySQL client in DIRACOS to 8.0 or higher and implement backwards compatibility for 5.X. (DIRACOS bundling + DIRAC code)
2. Changing authentication method for both Dirac and admin users using `ALTER USER admin
IDENTIFIED WITH mysql_native_password
BY 'password';` (DIRAC code)

**Comment by chaen** [comment]
Currently, the MySQL version we support is up to 5.7 
I would just not use the `mysql:latest` container. It's too many problems tackled at the same time in my opinion

**Comment by antolu** [comment]
Indeed. Just leaving this here for the future.

**Comment by chaen** [comment]
From @chrisburr (https://github.com/DIRACGrid/DIRACOS/issues/97#issuecomment-535438554):
```
5.7.23 or later is required for MySQL 8.0 so the caching_sha2_password module is included.
```
