### ISSUE TITLE
Add Singularity

### ISSUE THREAD

**Issue by chrisburr** [DIRACGrid/DIRACOS#96]
Should be compiled with setuid support disabled

**Comment by chaen** [comment]
This is quite on the heavy side:
From @petricm 
```RPM 30 MB install size 90 MB```

**Comment by chrisburr** [comment]
It's not completely hopeless, I trivially managed to shrink my installation to 12M packed 34M installed.

**Comment by chaen** [comment]
again: no dirty trick in DIRACOS. Take an SRPM, eventually patch the spec file, and that's about it. If several RPMs are generated out of that (devel, doc, lib, whatever), we can selectively take them. But that's it

**Comment by chrisburr** [comment]
I agree entirely 👍 

Provided a small patch to the spec file are acceptable it should be easy to use the suggestions here to add a couple of build flags that prevent debug information being included: https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

**Comment by chaen** [comment]
OK, then I suggest that we look at it together when I'm back (when I say together, I mean you try the doc, and I correct it straight away, in a quick iterative manner :D )

**Comment by petricm** [comment]
the srpm is already uploaded [here](http://diracos.web.cern.ch/diracos/SRPM/singularity-3.4.0-1.2.el6.src.rpm)

**Comment by petricm** [comment]
@chrisburr did you try to do a test build, to see how much does Singularity increase the size?
